us4 - pedido de servio de quarto
BrunoRRamos/Our-Hotel-Haskell pull request #22
Opened 2024-03-25 23:38 UTC by SuelenFelix

2024-03-28 12:03 UTC, gabrielmeloc22 requested changes

2024-03-28 12:03 UTC, gabrielmeloc22 commented on src/Rooms.hs
> +      when (service == Service 0 0 CLEANING "" 0) $ putStrLn "Service not found"
acredito que esse check não funcione,  porque o getService retorna um service ou dá um erro quando não encontra.  o que vc poderia fazer aqui eh mudar o getService pra retornar um valor opcional (e.g `Maybe Service`) e dai tratar isso com um case. Tipo assim:
```hs
service <- getService conn sid
case service of
    Just s -> do
         -- faz algo aqui com o service encontrado
    Nothing -> do
          -- indica que não achou e volta pro menu ou chama a função de novo
```

2024-03-28 12:03 UTC, gabrielmeloc22 commented on src/Models/Service.hs
> +  services <- query conn "SELECT * FROM service WHERE reservation_id = ?" (Only reservationId) :: IO [Service]
a gente infelizmente não pode usar where nas chamadas ao banco de dados por causa daquilo que o professor disse, só pega todos os services e usa um filter que dá no mesmo. Seria algo assim:
```suggestion
  allServices <- getAllServices conn
  let services = filter (\service -> _reservationId service == reservationId) services
```

2024-03-28 12:03 UTC, gabrielmeloc22 commented on src/Utils/Hospede.hs
> +    _ <- getCurrentTime
essa chamada aqui pode ser removida, o retorno não está sendo usado, certo?

2024-03-28 12:03 UTC, gabrielmeloc22 commented on src/Utils/Hospede.hs
> +    let service = Service { _id = 0, _price = price, _type = serviceType, _description = description, _reservationId = reservationId }
não precisa passar o id, mas pode deixar assim, a lsp fica reclamando quando vc não passa todos os campos de um objeto, tem como desabilitar isso com um flag lá em cima também!

2024-03-28 12:03 UTC, gabrielmeloc22 commented on Our-Hotel.cabal
> +      Lib
esse arquivo lib pode ser removido, só apagar o arquivo Lib.hs e rodar stack install que acredito que some desse arquivo .cabal

2024-03-28 12:03 UTC, gabrielmeloc22 commented on src/Models/Service.hs
> +  services <- query conn "SELECT * FROM service WHERE reservation_id = ?" (Only reservationId) :: IO [Service]
eu sugiro criar uma função que faz justamente isso : pegar serviços por reserva, e dai o calculatePrice só recebe uma lista de serviços e faz uma soma, porque vc pode tratar os erros melhor, se não tem serviços para aquela reserva ou se a reserva n foi encontrada, etc

2024-03-28 17:04 UTC, PedroCost4 requested changes

2024-03-28 17:04 UTC, PedroCost4 commented on src/Models/Service.hs
> +printService :: Service -> IO ()
Eu acredito que fique melhor fazendo uma instancia de show no model de service, que ai é qualquer show (ou print) ele vai mostrar desse modelo ai

2024-03-28 17:04 UTC, PedroCost4 commented on src/Rooms.hs
> +  putStrLn "1.  list_rooms"
como vamos usar os números pra caminhar pelos menus, melhor ter uma Explicacão certinha desse menu, tipo `1. List all rooms`

2024-03-28 17:04 UTC, PedroCost4 commented on src/Util/Hospede.hs
> +    let service = Service { _id = 0, _price = price, _type = serviceType, _description = description, _reservationId = reservationId }
Não precisa passar o Id nesse caso, é só usar uma language do haskell para o lsp entender

2024-03-28 17:04 UTC, PedroCost4 commented on src/Util/HospedeLoop.hs
> +      result <- try $ requestRoomService conn 1 50 CLEANING "Clean the room" :: IO (Either SomeException ())
Nesse caso, porque o reservationId que está sendo passado é sempre 1? precisariamos pedir o input do usuario pra saber em qual reserva o room service vai acontecer

2024-03-28 23:53 UTC, gabrielmeloc22 approved these changes

2024-03-28 23:53 UTC, gabrielmeloc22 commented on src/Rooms.hs
> +      conn <- startDb
a ideia é a gente manter uma única conexão com o banco de dados, então seria bom só repassar ela pra o roomsLoop, mas pode deixar assim que acho que depois a gente pode dar uma revisada, porque tem outros jeitos de ter essa conexão em qualquer lugar!

2024-03-29 00:18 UTC, PedroCost4 approved these changes

2024-03-29 01:07 UTC, merged