Criada a funcao de avaliacao de estadia
BrunoRRamos/Our-Hotel-Haskell pull request #24
Opened 2024-03-28 23:39 UTC by Pedro1Jose

2024-03-30 14:50 UTC, PedroCost4 requested changes

2024-03-30 14:50 UTC, PedroCost4 commented on src/Util/StayReview.hs
> +    return $ StayReview
quase tudo certinho, só faltou aqui ao inves de retornar o stay review, tem que inserir ele na tabela que tu criou

2024-03-30 20:59 UTC, gabrielmeloc22 submitted a review, later dismissed

2024-03-30 20:59 UTC, gabrielmeloc22 commented on src/Models/Review.hs
> +      \reservation_id INTEGER,\
a table tá certinha, mas aqui a gente precisa indicar que o reservation_id aponta pra uma reserva que tá na tabela de reservation, dá uma olhada nos outros modelos, tem código parecido

2024-03-30 20:59 UTC, gabrielmeloc22 commented on src/Util/StayReview.hs
> +    putStrLn "Review added successfully!"
pode usar a função de insertReview aqui já que ela foi criada!

2024-03-30 20:59 UTC, gabrielmeloc22 commented on src/Models/Review.hs
> +  fromRow = Review <$> field <*> field <*> field <*> field <*> field <*> field
pega o exemplo que tem na table de reserva. a gente não precisa declarar os fields todos e também precisamos tratar o campo de data, no modelo de reserva tem tudo isso!

2024-03-30 20:59 UTC, gabrielmeloc22 commented on src/Models/Review.hs
No geral, tá no caminho certo, mas precisa colocar essas funçoes em uso no menu, pelo menos pegar os inputs e fazer algumas validações

2024-04-01 12:34 UTC, PedroCost4 approved these changes

2024-04-01 20:54 UTC, BrunoRRamos approved these changes
Aprovado

2024-04-01 20:54 UTC, SuelenFelix approved these changes

2024-04-01 20:54 UTC, SuelenFelix commented on src/Models/Review.hs
> +        userId :: String
Não há necessidade de ligar a avaliação com o usuário, podemos fazer ela de forma anônima.

2024-04-01 20:55 UTC, merged